### ISSUE TITLE
Comming up next

### ISSUE THREAD

**Issue by 3vilcookie** [3vilcookie/femto#30]
Feature discussion issue.

# Next
- [x]  `<DELETE>` key binding #23 
- [x] `<TAB>` key binding #20 
- [x] Fix missing last line on save if empty #26 
- [ ] Fix dissapearing char at eol #21 

# Not scheduled
- Title bar animation like bisqwit's [that_editor](https://github.com/bisqwit/that_editor)
- Syntax highlighting
- Home/End key binding
- Page up/down key binding
